development:
  adapter: postgresql
  encoding: unicode
  database: fyber_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: fyber_test
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  database: fyber_staging
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: fyber_production
  pool: 5